// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { UsbDataType } from './usb-data-type.js';


export class UsbPacket {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UsbPacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUsbPacket(bb:flatbuffers.ByteBuffer, obj?:UsbPacket):UsbPacket {
  return (obj || new UsbPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUsbPacket(bb:flatbuffers.ByteBuffer, obj?:UsbPacket):UsbPacket {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UsbPacket()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():UsbDataType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : UsbDataType.NONE;
}

platform():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
}

sequence():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

data(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

dataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

dataArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startUsbPacket(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addType(builder:flatbuffers.Builder, type:UsbDataType) {
  builder.addFieldInt8(0, type, UsbDataType.NONE);
}

static addPlatform(builder:flatbuffers.Builder, platform:number) {
  builder.addFieldInt8(1, platform, 0);
}

static addSequence(builder:flatbuffers.Builder, sequence:number) {
  builder.addFieldInt16(2, sequence, 0);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, dataOffset, 0);
}

static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endUsbPacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUsbPacket(builder:flatbuffers.Builder, type:UsbDataType, platform:number, sequence:number, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  UsbPacket.startUsbPacket(builder);
  UsbPacket.addType(builder, type);
  UsbPacket.addPlatform(builder, platform);
  UsbPacket.addSequence(builder, sequence);
  UsbPacket.addData(builder, dataOffset);
  return UsbPacket.endUsbPacket(builder);
}
}
