// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum UsbDataType {
  NONE = 0,
  SET_SE_MODE = 1,
  SE_LATENCY = 2,
  OPUS_LATENCY = 3,
  AUDIO_DATA = 4
}
