// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_USBDATA_H_
#define FLATBUFFERS_GENERATED_USBDATA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

struct UsbPacket;
struct UsbPacketBuilder;

enum UsbDataType : int8_t {
  UsbDataType_NONE = 0,
  UsbDataType_SET_SE_MODE = 1,
  UsbDataType_SE_LATENCY = 2,
  UsbDataType_OPUS_LATENCY = 3,
  UsbDataType_AUDIO_DATA = 4,
  UsbDataType_MIN = UsbDataType_NONE,
  UsbDataType_MAX = UsbDataType_AUDIO_DATA
};

inline const UsbDataType (&EnumValuesUsbDataType())[5] {
  static const UsbDataType values[] = {
    UsbDataType_NONE,
    UsbDataType_SET_SE_MODE,
    UsbDataType_SE_LATENCY,
    UsbDataType_OPUS_LATENCY,
    UsbDataType_AUDIO_DATA
  };
  return values;
}

inline const char * const *EnumNamesUsbDataType() {
  static const char * const names[6] = {
    "NONE",
    "SET_SE_MODE",
    "SE_LATENCY",
    "OPUS_LATENCY",
    "AUDIO_DATA",
    nullptr
  };
  return names;
}

inline const char *EnumNameUsbDataType(UsbDataType e) {
  if (::flatbuffers::IsOutRange(e, UsbDataType_NONE, UsbDataType_AUDIO_DATA)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesUsbDataType()[index];
}

struct UsbPacket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UsbPacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_PLATFORM = 6,
    VT_SEQUENCE = 8,
    VT_DATA = 10
  };
  UsbDataType type() const {
    return static_cast<UsbDataType>(GetField<int8_t>(VT_TYPE, 0));
  }
  int8_t platform() const {
    return GetField<int8_t>(VT_PLATFORM, 0);
  }
  uint16_t sequence() const {
    return GetField<uint16_t>(VT_SEQUENCE, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_PLATFORM, 1) &&
           VerifyField<uint16_t>(verifier, VT_SEQUENCE, 2) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct UsbPacketBuilder {
  typedef UsbPacket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(UsbDataType type) {
    fbb_.AddElement<int8_t>(UsbPacket::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_platform(int8_t platform) {
    fbb_.AddElement<int8_t>(UsbPacket::VT_PLATFORM, platform, 0);
  }
  void add_sequence(uint16_t sequence) {
    fbb_.AddElement<uint16_t>(UsbPacket::VT_SEQUENCE, sequence, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(UsbPacket::VT_DATA, data);
  }
  explicit UsbPacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UsbPacket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UsbPacket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UsbPacket> CreateUsbPacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    UsbDataType type = UsbDataType_NONE,
    int8_t platform = 0,
    uint16_t sequence = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  UsbPacketBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_sequence(sequence);
  builder_.add_platform(platform);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UsbPacket> CreateUsbPacketDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    UsbDataType type = UsbDataType_NONE,
    int8_t platform = 0,
    uint16_t sequence = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return CreateUsbPacket(
      _fbb,
      type,
      platform,
      sequence,
      data__);
}

#endif  // FLATBUFFERS_GENERATED_USBDATA_H_
